nelmio_api_doc:
    documentation:
        info:
            title: News App
            description: Test project for QTIM
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/auth
            - ^/api(?!/doc.json$)
            
